/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OptimizeRouteImport } from './routes/optimize'
import { Route as CampaignsCampaignIdRouteRouteImport } from './routes/campaigns/$campaignId/route'
import { Route as WorkflowsWorkflowIdRouteRouteImport } from './routes/workflows/$workflowId/route'
import { Route as CampaignsCampaignIdIndexRouteImport } from './routes/campaigns/$campaignId/index'
import { Route as WorkflowsWorkflowIdIndexRouteImport } from './routes/workflows/$workflowId/index'
import { Route as CampaignsCampaignIdRunsRunIdRouteImport } from './routes/campaigns/$campaignId/runs/$runId'
import { Route as WorkflowsWorkflowIdRunsRunIdRouteImport } from './routes/workflows/$workflowId/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizeRoute = OptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRouteRoute =
  CampaignsCampaignIdRouteRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsWorkflowIdRouteRoute =
  WorkflowsWorkflowIdRouteRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdIndexRoute =
  CampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const WorkflowsWorkflowIdIndexRoute =
  WorkflowsWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkflowsWorkflowIdRouteRoute,
  } as any)
const CampaignsCampaignIdRunsRunIdRoute =
  CampaignsCampaignIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => CampaignsCampaignIdRouteRoute,
  } as any)
const WorkflowsWorkflowIdRunsRunIdRoute =
  WorkflowsWorkflowIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => WorkflowsWorkflowIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/optimize': typeof OptimizeRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRouteWithChildren
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteRouteWithChildren
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/workflows/$workflowId/': typeof WorkflowsWorkflowIdIndexRoute
  '/campaigns/$campaignId/runs/$runId': typeof CampaignsCampaignIdRunsRunIdRoute
  '/workflows/$workflowId/runs/$runId': typeof WorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/optimize': typeof OptimizeRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdIndexRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdIndexRoute
  '/campaigns/$campaignId/runs/$runId': typeof CampaignsCampaignIdRunsRunIdRoute
  '/workflows/$workflowId/runs/$runId': typeof WorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/optimize': typeof OptimizeRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteRouteWithChildren
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteRouteWithChildren
  '/campaigns/$campaignId/': typeof CampaignsCampaignIdIndexRoute
  '/workflows/$workflowId/': typeof WorkflowsWorkflowIdIndexRoute
  '/campaigns/$campaignId/runs/$runId': typeof CampaignsCampaignIdRunsRunIdRoute
  '/workflows/$workflowId/runs/$runId': typeof WorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/optimize'
    | '/campaigns/$campaignId'
    | '/workflows/$workflowId'
    | '/campaigns/$campaignId/'
    | '/workflows/$workflowId/'
    | '/campaigns/$campaignId/runs/$runId'
    | '/workflows/$workflowId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/optimize'
    | '/campaigns/$campaignId'
    | '/workflows/$workflowId'
    | '/campaigns/$campaignId/runs/$runId'
    | '/workflows/$workflowId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/optimize'
    | '/campaigns/$campaignId'
    | '/workflows/$workflowId'
    | '/campaigns/$campaignId/'
    | '/workflows/$workflowId/'
    | '/campaigns/$campaignId/runs/$runId'
    | '/workflows/$workflowId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OptimizeRoute: typeof OptimizeRoute
  CampaignsCampaignIdRouteRoute: typeof CampaignsCampaignIdRouteRouteWithChildren
  WorkflowsWorkflowIdRouteRoute: typeof WorkflowsWorkflowIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimize': {
      id: '/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof OptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/': {
      id: '/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof CampaignsCampaignIdIndexRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/workflows/$workflowId/': {
      id: '/workflows/$workflowId/'
      path: '/'
      fullPath: '/workflows/$workflowId/'
      preLoaderRoute: typeof WorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRouteRoute
    }
    '/campaigns/$campaignId/runs/$runId': {
      id: '/campaigns/$campaignId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/campaigns/$campaignId/runs/$runId'
      preLoaderRoute: typeof CampaignsCampaignIdRunsRunIdRouteImport
      parentRoute: typeof CampaignsCampaignIdRouteRoute
    }
    '/workflows/$workflowId/runs/$runId': {
      id: '/workflows/$workflowId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workflows/$workflowId/runs/$runId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRunsRunIdRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRouteRoute
    }
  }
}

interface CampaignsCampaignIdRouteRouteChildren {
  CampaignsCampaignIdIndexRoute: typeof CampaignsCampaignIdIndexRoute
  CampaignsCampaignIdRunsRunIdRoute: typeof CampaignsCampaignIdRunsRunIdRoute
}

const CampaignsCampaignIdRouteRouteChildren: CampaignsCampaignIdRouteRouteChildren =
  {
    CampaignsCampaignIdIndexRoute: CampaignsCampaignIdIndexRoute,
    CampaignsCampaignIdRunsRunIdRoute: CampaignsCampaignIdRunsRunIdRoute,
  }

const CampaignsCampaignIdRouteRouteWithChildren =
  CampaignsCampaignIdRouteRoute._addFileChildren(
    CampaignsCampaignIdRouteRouteChildren,
  )

interface WorkflowsWorkflowIdRouteRouteChildren {
  WorkflowsWorkflowIdIndexRoute: typeof WorkflowsWorkflowIdIndexRoute
  WorkflowsWorkflowIdRunsRunIdRoute: typeof WorkflowsWorkflowIdRunsRunIdRoute
}

const WorkflowsWorkflowIdRouteRouteChildren: WorkflowsWorkflowIdRouteRouteChildren =
  {
    WorkflowsWorkflowIdIndexRoute: WorkflowsWorkflowIdIndexRoute,
    WorkflowsWorkflowIdRunsRunIdRoute: WorkflowsWorkflowIdRunsRunIdRoute,
  }

const WorkflowsWorkflowIdRouteRouteWithChildren =
  WorkflowsWorkflowIdRouteRoute._addFileChildren(
    WorkflowsWorkflowIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OptimizeRoute: OptimizeRoute,
  CampaignsCampaignIdRouteRoute: CampaignsCampaignIdRouteRouteWithChildren,
  WorkflowsWorkflowIdRouteRoute: WorkflowsWorkflowIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
